on: [push]
jobs: 
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Deploy site
              uses: cloudflare/pages-action@1
              with: 
                directory: 'dist'
                projectName: 'anjelica'
                gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}